### ISSUE TITLE
Mistake in section about \B

### ISSUE THREAD

**Issue by GhiathAjam** [Mostafa-wael/NLP-Lectures#1]
Pragraph talking about Non word Boundary:
> Non-Word Boundary: The \B matches a non-word boundary which is any word characters(digits, underscores, or letters).
E.g.: `/hello\B/` matches `hello` in `hello world` or `hello-world` or `helloworld`, but not `hello_world` and `hello5world`.

is wrong about many things.
Proof:
![image](https://user-images.githubusercontent.com/43111805/194440401-258e3266-ae61-4cf7-a74c-f6be0d045734.png)

Fix:
> Non-Word Boundary: The `\B` matches a non-word boundary === `[a-zA-Z0-9_]` i.e. a word character .
E.g.: `/hello\B/` matches `hello` in `hello5world`, `hello_world` and `helloworld`, but not in `hello-world` nor `hello world`.

**Comment by GhiathAjam** [comment]
Woke up an hour ago and couldnt get back to sleep :(
Also note that the paragraph talking about "Parenthesis" is fundamentally wrong, parenthesis are used for grouping characters together to allow operators to act on them as a group. 
`a?` => zero or more `a`
`abc?` => matches `ab` or `abc`
`a(bc)?` => matches `a` or `abc`
and so on for other operators.

other usage for parenthesis is for later using the matched group of characters.
E.g.: `s/ab(\d)/\1ef` or `s/ab(\d)/$1ef` will:
- match `ab5` and replace it with `5ef`.
- match `ab0` and replace it with `0ef`.

(syntax for substitution command is `s/<search regex>/<substiution regex>`)

**Comment by Mostafa-wael** [comment]
> Pragraph talking about Non word Boundary:
> 
> > Non-Word Boundary: The \B matches a non-word boundary which is any word characters(digits, underscores, or letters).
> > E.g.: `/hello\B/` matches `hello` in `hello world` or `hello-world` or `helloworld`, but not `hello_world` and `hello5world`.
> 
> is wrong about many things. Proof: ![image](https://user-images.githubusercontent.com/43111805/194440401-258e3266-ae61-4cf7-a74c-f6be0d045734.png)
> 
> Fix:
> 
> > Non-Word Boundary: The `\B` matches a non-word boundary === `[a-zA-Z0-9_]` i.e. a word character .
> > E.g.: `/hello\B/` matches `hello` in `hello5world`, `hello_world` and `helloworld`, but not in `hello-world` nor `hello world`.

Thanks for the note, the regex itself was wrong. I meant to write another one that fits the example but mistyped it, thanks again!
